language: haskell

env:
# - GHCVER=7.6.3 CABALVER=1.18
  - GHCVER=7.8.4 CABALVER=1.20
  - GHCVER=7.10 CABALVER=1.21
  - GHCVER=head  CABALVER=head

matrix:
  allow_failures:
   - env: GHCVER=head  CABALVER=head
   - env: GHCVER=7.10  CABALVER=1.21

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install libblas-dev liblapack-dev
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - cabal --version
 - ghc --version

install:
 - sudo /opt/ghc/$GHCVER/bin/ghc-pkg recache
 - /opt/ghc/$GHCVER/bin/ghc-pkg recache --user
 - cabal update
 - cabal sandbox init
 - cabal install --only-dependencies --enable-tests --enable-benchmarks  --max-backjumps=10000

script:
 - cabal configure
 - cabal build
# - cabal test
